// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btnowklhetccqldnkxps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0bm93a2xoZXRjY3FsZG5reHBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNTg4NDAsImV4cCI6MjA2OTYzNDg0MH0.YN8bzTGZcyagXuXyxVRq5t94NWxSRgnu3Y7AncpCpuU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});